// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmrbcdabbfmyvtazikem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptcmJjZGFiYmZteXZ0YXppa2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NDMxMTgsImV4cCI6MjA1NDQxOTExOH0.F_ygPk35Ty7SQlVNUmmN3Ff0rQWiu21_WopLT8Ios-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);